name: tjbioinformatic
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: ^3.6.0

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.2
  cupertino_icons: ^1.0.8

  app_settings: ^5.1.1
  font_awesome_flutter: ^10.0.0
  supabase_flutter: ^2.8.3

  get: ^4.6.5
  permission_handler: ^11.2.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.9


flutter:
  uses-material-design: true
  
  assets:
    
    # Add asset paths here if needed
    # - assets/images/
    - assets/

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
